feeds/urls.py
from django.conf.urls.defaults import *

import views

urlpatterns = patterns('',
    # tweets
    url(r'^map$', views.tweets_map, name='tweets-map'),
    url(r'^tweets$', views.tweets_list, name='tweets-list'),
    url(r'^tweet/(?P<id>\d+)/detail$', views.tweet_detail, name='tweet-detail'),
    
    # places
    url(r'^places$', views.places_list, name='places-list'),
    url(r'^places/(?P<place_slug>[-\w]+)/detail$', views.place_detail, name='place-detail'),
    
    # searches
    url(r'^searches$', views.searches_list, name='searches-list'),
    
    # people
    url(r'^people$', views.people_list, name='people-list'),
    url(r'^people/(?P<person_slug>[-\w]+)/detail$', views.person_detail, name='person-detail'),
    
    # domains
    url(r'^domains$', views.domains_list, name='domains-list'),
    url(r'^domains/(?P<id>\d+)/detail$', views.domain_detail, name='domain-detail'),
    
    # keywords
    url(r'^keyword/(?P<keyword_name>[-\w]+)/detail$', views.keyword_detail, name='keyword-detail'),
    
    # tags
    url(r'^tags$', views.tags_list, name='tags-list'),
    url(r'^tags/(?P<tag_slug>[-\w]+)/detail$', views.tag_detail, name='tag-detail'),
    
    # update methods
    url(r'^item/(?P<id>\d+)/archive$', views.item_archive, name='item-archive'),
    # json methods
    url(r'^feeds/class/(?P<feedclass>\w+)/list$', views.list_feeds_for_class, name='list-feeds-for-class'),
    # kml output
    url(r'^kml/places/$', views.get_kml_places, name='places-kml'),
    # filters
    url(r'^filters/$', views.filters, name='filters'),
    # test
    url(r'^test/$', views.test, name='test'),
)

urls.py
import os

# django batteries
from django.conf.urls.defaults import *
from django.conf import settings
from django.core.urlresolvers import reverse

# admin
from django.contrib import admin
admin.autodiscover()

from feeds.views import searches_list

urlpatterns = patterns('',

    # home page
    #url(r'^$', tweets_map, name='tweets-map'),
    url(r'^$', searches_list, name='searches-list'),
    
    # admin url
    (r'^admin/', include(admin.site.urls)),

    # feeds url
    (r'^feeds/', include('feeds.urls')),
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(os.path.dirname(__file__), "media"),
             'show_indexes': True
            }),
    )

feeds/models.py
# python
import urlparse
# django
from django.db import models
from django.contrib.gis.db import models as gismodels
from django.db.models.signals import pre_save, pre_delete
# django-taggit
from taggit.managers import TaggableManager

class Country(gismodels.Model):
    """
    Spatial model for Countries.
    """
    # attributes
    name = gismodels.CharField(max_length=50)
    fips = gismodels.CharField(max_length=2)
    iso2 = gismodels.CharField(max_length=2)
    iso3 = gismodels.CharField(max_length=3)
    geometry = gismodels.MultiPolygonField(srid=4326)
    objects = gismodels.GeoManager()

    def __unicode__(self):
        return '%s' % (self.name)
        
    class Meta:
        ordering = ['name']
        verbose_name_plural = "Countries"
        
class Domain(models.Model):
    """
    Model for Internet Domain.
    """
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country, null=True)
    
    def __unicode__(self):
        return '%s' % (self.name)
    
    class Meta:
        ordering = ['name']

class Feed(models.Model):
    """
    Model for Feeds.
    """
    # attributes
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    url_xml = models.URLField(max_length=255)
    url_html = models.URLField(max_length=255)
    enabled = models.BooleanField()
    icon = models.ImageField(null=True, blank=True, upload_to='feeds')
    tags = TaggableManager()

    def __unicode__(self):
        return '%s' % (self.name)

    def unarchived(self):
        return self.item_set.all().filter(archived=False).count()
        
    class Meta:
        ordering = ['name']

class Place(gismodels.Model):
    """
    Spatial model for Countries.
    """
    # attributes
    name = gismodels.CharField(max_length=255)
    slug = gismodels.SlugField(max_length=255)
    geometry = gismodels.PointField(srid=4326)
    #tweets = models.ManyToManyField(Tweet, null=True, blank=True)
    from_gps = gismodels.BooleanField()
    country = models.ForeignKey(Country, null=True, blank=True) # derived
    objects = gismodels.GeoManager()

    def __unicode__(self):
        return '%s' % (self.name)
        
class Item(models.Model):
    """
    Model for Items.
    """
    # attributes
    title = models.CharField(max_length=255)
    summary = models.TextField()
    updated = models.DateTimeField(null=True)
    link = models.TextField()
    #places = models.ManyToManyField(Place, null=True, blank=True)

    def __unicode__(self):
        return '%s' % (self.title)
        
class Tweet(models.Model):
    """
    Model for Tweets.
    """
    # attributes
    twitter_id = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    created_at = models.DateTimeField(null=True)
    user_name = models.CharField(max_length=255)
    screen_name = models.URLField(max_length=255)
    filtered = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    places = models.ManyToManyField(Place, null=True, blank=True)
    
    tags = TaggableManager()

    def item_type(self):
        if self.archived:
            return 'archived-item'
        if self.filtered:
            return 'filtered-item'
        return 'simple-item'

    def __unicode__(self):
        return '%s' % (self.status)
        
    def the_places(self):
        return "\n".join([p.name for p in self.places.all()])
        
    def the_searches(self):
        return "\n".join([s.name for s in self.search_set.all()])
        
class Person(gismodels.Model):
    """
    Model for Person.
    """
    # attributes
    name = models.CharField(max_length=255)
    full_name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    tweets = models.ManyToManyField(Tweet, null=True, blank=True)

    def __unicode__(self):
        return '%s' % (self.name)
        
    class Meta:
        ordering = ['name']
        verbose_name_plural = "People"
        
class Keyword(gismodels.Model):
    """
    Model for Keyword.
    """
    # attributes
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __unicode__(self):
        return '%s' % (self.name)
        
class Search(gismodels.Model):
    """
    Spatial model for Search.
    """
    # attributes
    name = gismodels.CharField(max_length=50)
    geometry = gismodels.MultiPolygonField(srid=4326)
    keywords = models.ManyToManyField(Keyword, null=True, blank=True)
    tweets = models.ManyToManyField(Tweet, null=True, blank=True)
    #items = models.ManyToManyField(Item, null=True, blank=True)
    is_enabled = models.BooleanField()
    objects = gismodels.GeoManager()

    def __unicode__(self):
        return '%s' % (self.name)
        
    class Meta:
        ordering = ['name']
        verbose_name_plural = "Searches"
        
    def the_keywords(self):
        return "\n".join([k.name for k in self.keywords.all()])
        
class Image(gismodels.Model):
    """
    Model for Image.
    """
    # attributes
    src = models.CharField(max_length=255)
    alt = models.CharField(max_length=255)
    item = models.ForeignKey(Item)

    def __unicode__(self):
        return '%s' % (self.alt)
    
class Filter(models.Model):
    """
    Model for Filter.
    """
    # attributes
    keywords = models.TextField()  
    # TODO maybe we may have a keywords list for each feed? For now is global
    # TODO maybe we have a end date for a certain filter? For now is manual

### signals

def place_pre_save(sender, **kwargs):
    # country
    place = kwargs["instance"]
    rsc = Country.objects.filter(geometry__contains=place.geometry)
    if rsc.count()>0:
        country = rsc[0]
        place.country = country
        
#def search_pre_delete(sender, **kwargs):
#    search = kwargs["instance"]
#    import ipdb;ipdb.set_trace()
#    for tweet in search.tweets.all():
#        if tweet.search_set.count()==1:
#            tweet.delete()
       
pre_save.connect(place_pre_save, sender=Place)
#pre_delete.connect(search_pre_delete, sender=Search)

feeds/forms.py
import floppyforms as forms

class GMapPointWidget(forms.gis.PointWidget, forms.gis.BaseGMapWidget):
    map_width = 700
    map_height = 300
    template_name = 'forms/place_detail.html'
    
class PlaceForm(forms.ModelForm):
    geometry = forms.gis.PointField(widget=GMapPointWidget)

feeds/templates/template_tags/domain.html
<!-- Country code domain -->
{% load static %}

{% if item.domain.country %}
    Domain: <img src="{% get_static_prefix %}feeds/images/flags/{{ item.domain.country.iso2|lower }}.gif" alt="{{ item.domain.country.name }}" title="{{ item.domain.country.name }}" />
    <a href="{% url "domain-detail" item.domain.id %}">{{ item.domain.name }}</a>
{% endif %}

feeds/templates/template_tags/images_long.html
<!-- images long list -->
{% if images %}
    This news contains the following images:
    <ul>
    {% for image in images %}
    <li>
        <img src="{{ image.src }}" />
    </li>
    {% endfor %}
</ul>
{% endif %}

feeds/templates/template_tags/images_short.html
<!-- images short list -->
{% if count > 0 %}
    Images for this item: {{ count }}
    <br />
{% endif %}

feeds/templates/template_tags/keywords_long.html
<!-- keywords long list -->
{% if keywords %}
    This news may refer to the following keywords:
    <ul>
    {% for keyword in keywords %}
    <li>
        <a href="{% url "keyword-detail" keyword.name %}">{{ keyword.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

feeds/templates/template_tags/keywords_short.html
<!-- keywords short list -->
{% if keywords %}
    This news may refer to the following keywords:
    {% for keyword in keywords %}
        <a href="{% url "keyword-detail" keyword.name %}">{{ keyword.name }}</a>
    {% endfor %}
    <br />
{% endif %}

feeds/templates/template_tags/people_long.html
<!-- people long list -->
{% if people %}
    This news may refer to the following people:
    <ul>
    {% for person in people %}
    <li>
        <a href="{% url "person-detail" person.slug %}">{{ person.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

feeds/templates/template_tags/people_short.html
<!-- people short list -->
{% if people %}
    This news may refer to the following people:
    {% for person in people %}
        <a href="{% url "person-detail" person.slug %}">{{ person.name }}</a>
    {% endfor %}
    <br />
{% endif %}

feeds/templates/template_tags/places.html
<!-- places list -->
{% load static %}

{% if places %}
    <ul>
    {% for place in places %}
        <li>
            {% if place.country %}
                <img src="{% get_static_prefix %}feeds/images/flags/{{ place.country.iso2|lower }}.gif" alt="{{ place.country }}"  title="{{ place.country }}" />
            {% endif %}
            <a href="{% url "place-detail" place.slug %}">{{ place.name }}</a>
            {% if place.tweet_set.count > 1 %}
                (other {{ place.tweet_set.count }} tweets for this place)
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endif %}

feeds/templates/template_tags/show_place_map.html
<!-- Place map -->
{% load static %}

{% block media %}
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.css" />
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.ie.css" />
    <![endif]-->
    <script src="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.js"></script>
{% endblock %}

<div id="map" ></div>

<script>
    var map = new L.Map('map');
    var cloudmade = new L.TileLayer('http://{s}.tile.cloudmade.com/{{ cloudmade_api_key }}/997/256/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
        maxZoom: 18
    });
    
    // initial extent and zoom
    var latlon_init = new L.LatLng({{ place.geometry.y }}, {{ place.geometry.x }});
    map.setView(latlon_init, 13).addLayer(cloudmade);
    
    // let's add the marker
    var marker = new L.Marker(latlon_init);
    map.addLayer(marker);
    marker.bindPopup("<b>{{ place.name }}</b>");

</script>

feeds/templates/template_tags/show_places_map.html
{% load staticfiles %}

{% block media %}
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.css" />
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.ie.css" />
    <![endif]-->
    <script src="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.js"></script>
{% endblock %}

<div id="map"></div>

<script>
    var map = new L.Map('map');
    var cloudmade = new L.TileLayer('http://{s}.tile.cloudmade.com/{{ cloudmade_api_key }}/997/256/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
        maxZoom: 18
    });
    
    var Thunderforest_Landscape = L.tileLayer('http://{s}.tile3.opencyclemap.org/landscape/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>, &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
});
    
    // initial extent and zoom
    var latlon_init = new L.LatLng(0, 0);
    map.setView(latlon_init, 2).addLayer(Thunderforest_Landscape);
    
    // from search extent
    map.fitBounds([
        [{{ places.extent.1 }}, {{ places.extent.0 }}],
        [{{ places.extent.3 }}, {{ places.extent.2 }}]
    ]);

    // let's add the markers for places
    {% for place in places.all %}
         var markerPlace_{{ place.id }} = new L.LatLng({{ place.geometry.y }}, {{ place.geometry.x }});
        
        var myIcon = L.icon({
            {% if place.from_gps %}
                iconUrl: '{% static "feeds/images/twitter-icon-green-25.png" %}',
            {% else %}
                iconUrl: '{% static "feeds/images/twitter-icon-blue-25.png" %}',
            {% endif %}
            {% if place.tweet_set.all.count > 5 %}
                iconSize: [25,25],
            {% else %}
                iconSize: [15,15],
            {% endif %}
        });
        var marker_{{ place.id }} = new L.Marker(markerPlace_{{ place.id }}, {icon: myIcon});
        //var marker_{{ place.id }} = new L.Marker(markerPlace_{{ place.id }});

        map.addLayer(marker_{{ place.id }});
        var popup = "<strong><a href='{% url "place-detail" place.slug %}'>{{ place.name|linebreaksbr }}</a></strong>";
        popup = popup + "<br /><a href='https://twitter.com/{{ place.tweet_set.all.0.screen_name }}'>@{{ place.tweet_set.all.0.screen_name }}</a>, {{ place.tweet_set.all.0.created_at }}<br />";
        popup = popup + "<br />{{ place.tweet_set.all.0.status|linebreaksbr }}";
        
        {% if place.tweet_set.all.count > 1 %}
            popup = popup + "<br /><br />There are other {{ place.tweet_set.all.count|add:"-1" }} tweets for this place.<br /><a href='{% url "place-detail" place.slug %}'>See the full list</a>.";
        {% endif %}
        
        marker_{{ place.id }}.bindPopup(popup);
    {% endfor %}

    {% for e in events %}
        var eventIcon = L.icon({
                iconUrl: '{% static "feeds/images/feed_1.png" %}',
                iconSize: [15,15]
        });
        var markerEventPlace_{{ e.id }} = new L.LatLng({{ e.geometry.y }}, {{ e.geometry.x }});
        var markerEvent_{{ e.id }} = new L.Marker(markerEventPlace_{{ e.id }}, {icon: eventIcon});
        map.addLayer(markerEvent_{{ e.id }});
        var popup_event = "<strong>{{ e.eventcode.description }}</strong>";
        popup_event = popup_event + "<br />{{ e.date }}";
        popup_event = popup_event + "<br />Mentions: {{ e.num_mentions }}, Sources: {{ e.num_sources }}, Articles: {{ e.num_articles }}";
        popup_event = popup_event + "<br /><a href='{{ e.url }}'>{{ e.url|truncatechars:50 }}</a>"
        markerEvent_{{ e.id }}.bindPopup(popup_event);
    {% endfor %}
    
</script>
    

feeds/templates/template_tags/tags.html
<!-- tags -->
<br />Tagged as:
{% if tags %}
    {% for tag in tags %}
        <a href="{% url "tag-detail" tag.slug %}">{{ tag.name }}</a>
    {% endfor %}
{% endif %}